[package]
name = "RustyVulkan"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = {version = "0.38.0", features = ["linked"]}
ash-window = "0.13.0"
bytemuck = { version = "1.23", features = ["derive"] }
cgmath = "0.18.0"
libc = "0.2.174"
raw-window-handle = "0.6.2"
winit = "0.30.11"
imgui = "0.12"
imgui-winit-support = "0.13"
memoffset = "0.9.1"
image = "0.25.6"
fmt = "0.1.0"
vk-mem = "0.5"
russimp-ng = "3.2.7"

[build-dependencies]
shaderc = "0.9.1"
